language: python
python:
  - "2.7"

install: 
  - pip install -r requirements.txt
  - pip install .
script:
  - cedula -r 10000000-10000100 --db-file cedula.db
  - cedula -r 10000000-10000010 --show --db-file cedula.db
