language: python
python:
  - "2.7"
  - "3.4"

install: 
  - pip install -r requirements.txt
  - pip install .
script:
  - cedula -n V -r 10000000-10000100 -n 5 
  - cedula -n V -r 10000000-10000010 --show
